#include "cFileFinderTypes.hpp"   

    ACTIONSCRIPT_TYPES
    ADA_TYPES
    ASM_TYPES
    ASP_TYPES
    ASPX_TYPES
    BATCH_TYPES
    CC_TYPES
    CLOJURE_TYPES
    CMAKE_TYPES         
    COFFEE_TYPES        
    CPP__TYPES          
    CS_TYPES            
    CSS_TYPES           
    DART_TYPES          
    PAS_TYPES           
    EL_TYPES            
    EX_TYPES            
    ERL_TYPES           
    F_TYPES             
    GO_TYPES            
    GROOVY_TYPES        
    HS_TYPES            
    H_TYPES             
    HTM_TYPES           
    JAVA_TYPES          
    JS_TYPES            
    JSON_TYPES          
    JSP_TYPES           
    LESS_TYPES          
    LISP_TYPES          
    LUA_TYPES           
    MAKE_TYPES            
    MATLAB_TYPES             
    MKD_TYPES           
    M_TYPES             
    MM_TYPES            
    ML_TYPES            
    PIR_TYPES           
    PL_TYPES            
    T_TYPES             
    PHP_TYPES           
    PT_TYPES            
    PMC_TYPES           
    PY_TYPES            
    RAKE_TYPES          
    R_TYPES             
    RB_TYPES            
    RS_TYPES            
    SASS_TYPES          
    SCALA_TYPES         
    SCM_TYPES           
    SH_TYPES            
    ST_TYPES            
    SQL_TYPES           
    TCL_TYPES           
    TEX_TYPES           
    TEXTILE_TYPES       
    TT_TYPES            
    BAS_TYPES           
    V_TYPES             
    VHD_TYPES           
    VIM_TYPES           
    XML_TYPES           
    YAML_TYPES          
