#pragma once

#define ACTIONSCRIPT_TYPES  ".as", ".mxml",
#define ADA_TYPES           ".ada", ".adb", ".ads",
#define ASM_TYPES           ".asm", ".s",
#define ASP_TYPES           ".asp",
#define ASPX_TYPES          ".master", ".ascx", ".asmx", ".aspx", ".svc",
#define BATCH_TYPES         ".bat", ".cmd",
#define CC_TYPES            ".c", ".h", ".xs",
#define CFMX_TYPES          ".cfc", ".cfm", ".cfml",
#define CLOJURE_TYPES       ".clj",
#define CMAKE_TYPES         "CMakeLists.txt", ".cmake",
#define COFFEE_TYPES        ".coffee",
#define CPP__TYPES          ".cpp", ".cc", ".cxx", ".m", ".hpp", ".hh", ".h", ".hxx",
#define CS_TYPES            ".cs",
#define CSS_TYPES           ".css",
#define DART_TYPES          ".dart",
#define PAS_TYPES           ".pas", ".int", ".dfm", ".nfm", ".dof", ".dpk", ".dproj", ".groupproj", ".bdsgroup", ".bdsproj",
#define EL_TYPES            ".el",
#define EX_TYPES            ".ex", ".exs",
#define ERL_TYPES           ".erl", ".hrl",
#define F_TYPES             ".f", ".f77", ".f90", ".f95", ".f03", ".for", ".ftn", ".fpp",
#define GO_TYPES            ".go",
#define GROOVY_TYPES        ".groovy", ".gtmpl", ".gpp", ".grunit", ".gradle",
#define HS_TYPES            ".hs", ".lhs",
#define H_TYPES             ".h",
#define HTM_TYPES           ".htm", ".html",
#define JAVA_TYPES          ".java", ".properties",
#define JS_TYPES            ".js",
#define JSON_TYPES          ".json",
#define JSP_TYPES           ".jsp", ".jspx", ".jhtm", ".jhtml",
#define LESS_TYPES          ".less",
#define LISP_TYPES          ".lisp", ".lsp",
#define LUA_TYPES           ".lua", 
#define MAKE_TYPES          ".mk", "mak", "makefile", "Makefile", "GNUmakefile",
#define MATLAB_TYPES        ".m",
#define MKD_TYPES           ".mkd", ".md",
#define M_TYPES             ".m", ".h",
#define MM_TYPES            ".mm", ".h",
#define ML_TYPES            ".ml", ".mli",
#define PIR_TYPES           ".pir", ".pasm", ".pmc", ".ops", ".pod", ".pg", ".tg",
#define PL_TYPES            ".pl", ".pm", ".pod", ".t", ".psgi",
#define T_TYPES             ".t",
#define PHP_TYPES           ".php", ".phpt", ".php3", ".php4", ".php5", ".phtml",
#define PT_TYPES            ".pt", ".cpt", ".metadata", ".cpy", ".py",
#define PMC_TYPES           ".pmc",
#define PY_TYPES            ".py", 
#define RAKE_TYPES          "Rakefile",
#define R_TYPES             ".R",
#define RB_TYPES            ".rb", ".rhtml", ".rjs", ".rxml", ".erb", ".rake",
#define RS_TYPES            ".rs",
#define SASS_TYPES          ".sass", "scss",
#define SCALA_TYPES         ".scala",
#define SCM_TYPES           ".scm", ".ss",
#define SH_TYPES            ".sh", ".bash", ".csh", ".tcsh", ".ksh", ".zsh", ".fish",
#define ST_TYPES            ".st",
#define SQL_TYPES           ".sql", ".ctl",
#define TCL_TYPES           ".tcl", ".itcl", ".itk",
#define TEX_TYPES           ".tex", ".cls", ".sty",
#define TEXTILE_TYPES       ".textile",
#define TT_TYPES            ".tt", ".tt2", ".ttml",
#define BAS_TYPES           ".bas", ".cls", ".frm", ".ctl", ".vb", ".resx",
#define V_TYPES             ".v", ".vh", ".sv",
#define VHD_TYPES           ".vhd", ".vhdl",
#define VIM_TYPES           ".vim",
#define XML_TYPES           ".xml", ".dtd", ".xsl", ".xslt", ".ent", 
#define YAML_TYPES          ".yaml", "yml",                                                                                            

